blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/gitea
    about: Please ask questions and discuss configuration problems here.
  - name: Discourse Forum
    url: https://discourse.gitea.io
    about: Questions and configuration problems can also be discussed on the forum.    
  - name: Frequently Asked Questions
    url: https://docs.gitea.io/en-us/faq
    about: Please check if your question isn't mentioned here
  - name: Translations
    url: https://crowdin.com/project/gitea
    about: Translations are managed here.
